In [1]:
import numpy as np
i = np.array([
[10, 20, 30, 40, 50], # 0 - 0 1 2 3 4
[60, 70, 80, 90, 100] # 1 - 0 1 2 3 4
])
print(i[1, 0:3])

[60 70 80]


In [5]:
import numpy as np
p = np.array([
[15, 25, 35, 45, 55], # 0 - 0 1 2 3 4
[60, 70, 80, 90, 100] # 1 - 0 1 2 3 4
 ])
print(p[0, 1:4])

[25 35 45]


In [7]:
i = np.array([
 [10, 20, 30, 40, 50], # 0 - 0 1 2 3 4
 [60, 70, 80, 90, 100], # 1 - 0 1 2 3 4
 [11, 22, 33, 44, 55] # 2 - 0 1 2 3 4
 ])
print(i[2, 2:4])

[33 44]


In [8]:
import numpy as np
i = np.array([
 [10, 20, 30, 40, 50], # 0 - 0 1 2 3 4
 [60, 70, 80, 90, 100], # 1 - 0 1 2 3 4
 [11, 22, 33, 44, 55] # 2 - 0 1 2 3 4
 ])
print(i[0:2, 1])

[20 70]


In [9]:
import numpy as np
i = np.array([
[10, 20, 30, 40, 50], # 0 - 0 1 2 3 4
[60, 70, 80, 90, 100], # 1 - 0 1 2 3 4
[11, 22, 33, 44, 55], # 2 - 0 1 2 3 4
[1, 2, 3, 4, 5] # 2 - 0 1 2 3 4
])
print(i[0:3, 2])

[30 80 33]


In [10]:
import numpy as np
i = np.array([
 [10, 20, 30, 40, 50], # 0 - 0 1 2 3 4
 [60, 70, 80, 90, 100], # 1 - 0 1 2 3 4
 [11, 22, 33, 44, 55], # 2 - 0 1 2 3 4
 [1, 2, 3, 4, 5] # 2 - 0 1 2 3 4
 ])
print(i[0:4, 0:2])

[[10 20]
 [60 70]
 [11 22]
 [ 1  2]]


In [11]:
import numpy as np
i = np.array([
[10, 20, 30, 40, 50], # 0 - 0 1 2 3 4
[60, 70, 80, 90, 100], # 1 - 0 1 2 3 4
[11, 22, 33, 44, 55], # 2 - 0 1 2 3 4
[1, 2, 3, 4, 5] # 2 - 0 1 2 3 4
])
print(i[0:2, 2:4])

[[30 40]
 [80 90]]


In [13]:
import numpy as np
i = np.array([
 [10, 20, 30, 40, 50], # 0 - 0 1 2 3 4
 [60, 70, 80, 90, 100], # 1 - 0 1 2 3 4
 [11, 22, 33, 44, 55], # 2 - 0 1 2 3 4
 [1, 2, 3, 4, 5] # 2 - 0 1 2 3 4
 ])
print(i[0:3, -3:-1])

[[30 40]
 [80 90]
 [33 44]]
